const blackSesame = '#4A4A4A'
const maraschinoCherry = '#EF3E23'
const hintOfStrawberry = '#F7D3CB'
const lavender = '#ABB7E1'
const blueberry = '#7394E8'
const vanilla = '#F9F9F7'
const blackLiquorice = '#000000'
const seaSalt = '#DDDDDD'
const charcoal = '#9EA1AD'

export const pageBackground = vanilla
export const accentColor = maraschinoCherry
export const textColor = blackSesame
export const headerColor = blackLiquorice
export const lightBorder = hintOfStrawberry
export const lightGrayBorder = seaSalt
export const linkColor = lavender
export const darkLinkColor = blueberry
export const disabled = charcoal
