export const spacingSmall = '0.5rem'
export const spacingSmallish = '0.75rem'
export const spacingBase = '1rem'
export const spacingMedium = '1.5rem'
export const spacingLarge = '2rem'
export const spacingXLarge = '4rem'
export const spacingXXLarge = '6rem'
